steps:
  ### Copy files for APIScan
  - task: CopyFiles@2
    displayName: "Copy Files for APIScan"
    inputs:
      Contents: "*.vsix"
      TargetFolder: $(Agent.TempDirectory)/APIScanFiles
    condition: and(succeeded(), ne(variables['DisableAPIScan'], 'true'))

  ### Run latest version of APIScan listed at https://www.1eswiki.com/wiki/APIScan_Build_Task
  - task: APIScan@2
    displayName: Run APIScan
    inputs:
      softwareFolder: $(Agent.TempDirectory)/APIScanFiles
      softwareName: "vscode-azurespringcloud"
      softwareVersionNum: "$(Build.BuildId)"
      isLargeApp: false
      toolVersion: "Latest"
    condition: and(succeeded(), ne(variables['DisableAPIScan'], 'true'))
    env:
      AzureServicesAuthConnectionString: runAs=App;AppId=$(ApiScanClientId);TenantId=$(ApiScanTenant);AppKey=$(ApiScanSecret)
