steps:
  - task: Npm@1
    displayName: "npm ci"
    inputs:
      command: ci
  - task: Npm@1
    displayName: "Lint"
    inputs:
      command: custom
      customCommand: run lint
  - task: Npm@1
    displayName: "cleanReadme"
    inputs:
      command: custom
      customCommand: run cleanReadme
  - task: CmdLine@2
    displayName: Replace AI Key
    inputs:
      script: npx json@9.0.6 -I -f package.json -e "this.aiKey=\"$(AI_KEY)\""
