steps:
  - script: npx @vscode/vsce@latest generate-manifest -i extension.vsix -o extension.manifest
    displayName: "Generate extension manifest"
  - script: cp extension.manifest extension.signature.p7s
    displayName: "Prepare manifest for signing"
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@5
    displayName: "Sign extension"
    inputs:
      ConnectedServiceName: "ESRP-Release-Test"
      AppRegistrationClientId: "1992ee18-e9d2-42d6-ab20-94dd947a44b6"
      AppRegistrationTenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"
      AuthAKVName: "vscjavaci"
      AuthCertName: "vscjava-esrprelease-auth"
      AuthSignCertName: "VSCJava-CodeSign"
      FolderPath: "."
      Pattern: "extension.signature.p7s"
      signConfigType: inlineSignParams
      inlineOperation: |
        [
          {
            "keyCode": "CP-401405",
            "operationSetCode": "VSCodePublisherSign",
            "parameters" : [],
            "toolName": "sign",
            "toolVersion": "1.0"
          }
        ]
      SessionTimeout: 90
      MaxConcurrency: 25
      MaxRetryAttempts: 5
      PendingAnalysisWaitTimeoutMinutes: 5
