variables:
  Codeql.Enabled: true
  ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
    ENABLE_LONG_RUNNING_TESTS: true
    ENABLE_COMPLIANCE: true
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
trigger:
  branches:
    include:
      - main
pr:
  branches:
    include:
      - main
      - develop
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: 1ES_JavaTooling_Pool
      image: 1ES_JavaTooling_Windows_2022
      os: windows
    sdl:
      sourceAnalysisPool:
        name: 1ES_JavaTooling_Pool
        image: 1ES_JavaTooling_Windows_2022
        os: windows
    customBuildTags:
      - MigrationTooling-mseng-VSJava-AZURE-SPRING-Tool
    stages:
      - stage: Build
        jobs:
          - job: Linux
            displayName: build vsix
            templateContext:
              outputs:
                - output: pipelineArtifact
                  artifactName: drop
                  targetPath: $(build.artifactstagingdirectory)
                  displayName: "Publish Artifact: drop"
            steps:
              - checkout: self
                clean: true
                fetchTags: false
              - task: NodeTool@0
                displayName: 'Use Node 16.x'
                inputs:
                  versionSpec: 16.x
              - task: Npm@1
                displayName: 'npm ci'
                inputs:
                  command: ci
              - task: Npm@1
                displayName: 'Build'
                inputs:
                  command: custom
                  customCommand: run build
              - task: Npm@1
                displayName: 'Lint'
                inputs:
                  command: custom
                  customCommand: run lint
              - task: Npm@1
                displayName: 'cleanReadme'
                inputs:
                  command: custom
                  customCommand: run cleanReadme
              - task: CmdLine@2
                displayName: Replace AI Key
                inputs:
                  script: npx json@9.0.6 -I -f package.json -e "this.aiKey=\"$(AI_KEY)\""
              - task: Npm@1
                displayName: 'Package'
                inputs:
                  command: custom
                  customCommand: run package
                condition: ne(variables['ForPreRelease'], 'true')
              - task: Npm@1
                displayName: 'Package for Pre Release'
                inputs:
                  command: custom
                  customCommand: run package:pre-release
                condition: eq(variables['ForPreRelease'], 'true')
              ### Copy files for APIScan
              - task: CopyFiles@2
                displayName: "Copy Files for APIScan"
                inputs:
                  Contents: "**/*.vsix"
                  TargetFolder: $(Agent.TempDirectory)/APIScanFiles
                condition: and(succeeded(), ne(variables['DisableAPIScan'], 'true'))

              ### Run latest version of APIScan listed at https://www.1eswiki.com/wiki/APIScan_Build_Task
              - task: APIScan@2
                displayName: Run APIScan
                inputs:
                  softwareFolder: $(Agent.TempDirectory)/APIScanFiles
                  softwareName: "Azure Toolkit for Java"
                  softwareVersionNum: "$(Build.BuildId)"
                  isLargeApp: false
                  toolVersion: "Latest"
                condition: and(succeeded(), ne(variables['DisableAPIScan'], 'true'))
                env:
                  AzureServicesAuthConnectionString: runAs=App;AppId=$(ApiScanClientId);TenantId=$(ApiScanTenant);AppKey=$(ApiScanSecret)
              - task: CopyFiles@2
                displayName: 'Copy vsix to staging directory'
                inputs:
                  Contents: '**/*.vsix'
                  TargetFolder: '$(build.artifactstagingdirectory)'
