variables:
  Codeql.Enabled: true
  ForPreRelease: false
  ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
    ENABLE_LONG_RUNNING_TESTS: true
    ENABLE_COMPLIANCE: true
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
trigger:
  branches:
    include:
      - main
pr:
  branches:
    include:
      - main
      - develop
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: 1ES_JavaTooling_Pool
      image: 1ES_JavaTooling_Windows_2022
      os: windows
    sdl:
      sourceAnalysisPool:
        name: 1ES_JavaTooling_Pool
        image: 1ES_JavaTooling_Windows_2022
        os: windows
    customBuildTags:
      - MigrationTooling-mseng-VSJava-AZURE-SPRING-Tool
    stages:
      - stage: Build
        jobs:
          - job: Linux
            displayName: build vsix
            templateContext:
              outputs:
                - output: pipelineArtifact
                  artifactName: extension
                  targetPath: $(build.artifactstagingdirectory)
                  displayName: "Publish Artifact: extension"
            steps:
              - checkout: self
                clean: true
                fetchTags: true
              - template: common/build.yml
              - template: common/package.yml
              - template: common/apiscan.yml
              - template: common/sign.yml
              - template: common/publish.yml
