variables:
  Codeql.Enabled: true
  ForPreRelease: true
  ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
    ENABLE_LONG_RUNNING_TESTS: true
    ENABLE_COMPLIANCE: true
trigger: none
pr: none
schedules:
  - cron: "0 0 * * *"
    displayName: Daily 0am build
    branches:
      include:
        - main
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: 1ES_JavaTooling_Pool
      image: 1ES_JavaTooling_Windows_2022
      os: windows
    sdl:
      sourceAnalysisPool:
        name: 1ES_JavaTooling_Pool
        image: 1ES_JavaTooling_Windows_2022
        os: windows
    customBuildTags:
      - MigrationTooling-mseng-VSJava-AZURE-SPRING-Tool
    stages:
      - stage: Build
        jobs:
          - job: Linux
            displayName: build vsix
            templateContext:
              outputs:
                - output: pipelineArtifact
                  artifactName: extension
                  targetPath: $(build.artifactstagingdirectory)
                  displayName: "Publish Artifact: extension"
            steps:
              - checkout: self
                clean: true
                fetchTags: true
              - template: /.azure-pipelines/common/build.yml@self
              - template: /.azure-pipelines/common/package.yml@self
              - template: /.azure-pipelines/common/apiscan.yml@self
              - template: /.azure-pipelines/common/sign.yml@self
              - template: /.azure-pipelines/common/publish.yml@self
